export const UI_RESET_ERROR = 'UI_RESET_ERROR';

export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERT_LOADED_SUCCESS = 'ADVERT_LOADED_SUCCESS';

export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';

export const USER_AUTH_LOGIN_REQUEST = 'USER_AUTH_LOGIN_REQUEST';
export const USER_AUTH_LOGIN_SUCCESS = 'USER_AUTH_LOGIN_SUCCESS';
export const USER_AUTH_LOGIN_FAIL = 'USER_AUTH_LOGIN_FAIL';

export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
