export const UI_RESET_ERROR = 'UI_RESET_ERROR';

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAIL = 'ADVERTS_LOADED_FAIL';

export const ADVERT_LOADED_TAGS_REQUEST = 'ADVERT_LOADED_TAGS_REQUEST';
export const ADVERT_LOADED_TAGS_SUCCESS = 'ADVERT_LOADED_TAGS_SUCCESS';
export const ADVERT_LOADED_TAGS_FAIL = 'ADVERT_LOADED_TAGS_FAIL';

export const ADVERT_LOADED_REQUEST = 'ADVERT_LOADED_REQUEST';
export const ADVERT_LOADED_SUCCESS = 'ADVERT_LOADED_SUCCESS';
export const ADVERT_LOADED_FAIL = 'ADVERT_LOADED_FAIL';

export const ADVERTS_SET_FILTERS = 'ADVERTS_SET_FILTERS';
export const ADVERTS_DELETE_FILTERS = 'ADVERTS_DELETE_FILTERS';

export const ADVERT_CREATED_REQUEST = 'ADVERT_CREATED_REQUEST';
export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';
export const ADVERT_CREATED_FAIL = 'ADVERT_CREATED_FAIL';

export const ADVERT_DELETED_REQUEST = 'ADVERT_DELETED_REQUEST';
export const ADVERT_DELETED_SUCCESS = 'ADVERT_DELETED_SUCCESS';
export const ADVERT_DELETED_FAIL = 'ADVERT_DELETED_FAIL';

export const USER_AUTH_LOGIN_REQUEST = 'USER_AUTH_LOGIN_REQUEST';
export const USER_AUTH_LOGIN_SUCCESS = 'USER_AUTH_LOGIN_SUCCESS';
export const USER_AUTH_LOGIN_FAIL = 'USER_AUTH_LOGIN_FAIL';

export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
