export const USER_AUTH_LOGIN_REQUEST = 'USER_AUTH_LOGIN_REQUEST';
export const USER_AUTH_LOGIN_SUCCESS = 'USER_AUTH_LOGIN_SUCCESS';
export const USER_AUTH_LOGIN_FAIL = 'USER_AUTH_LOGIN_FAIL';

export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';